### ISSUE TITLE
We should use PolyMath random numbers generator instead of the Pharo

### ISSUE THREAD

**Issue by jordanmontt** [pharo-ai/data-generator#1]
Esteban experimented on this with a galaxy generator. We found that the random numbers generator in PolyMath performs better that the default one in Pharo. We should use PolyMath one

**Comment by Ducasse** [comment]
Definitively!!!!
I collected many of the algo in polymath so we can even copy one because in general they are so small that we can avoid the mess with dependencies.

**Comment by Ducasse** [comment]
We should also push in Pharo a better one.

**Comment by Ducasse** [comment]
Can you open an issue?

**Comment by jordanmontt** [comment]
I will open an issue and then do a PR to Pharo after ESUG :)

**Comment by jordanmontt** [comment]
Done: https://github.com/pharo-project/pharo/issues/11598

**Comment by jordanmontt** [comment]
For the record, this issue is still valid for this repo! pharo-ai. We need to use another random number generator :)

**Comment by jordanmontt** [comment]
I will close this as we saw that the pharo generating number behaves good. I will create other issue more specific
